package:
  name: byow
  version: 0.0.1

source:
  path: ../

requirements:
  build:
    - python={{ python_version }}
    - setuptools

  run:
    - python={{ python_version }}
    - pythonocc-core
    - pyqt
    - qtpy
    - qdarkstyle

about:
  home: https://github.com/joergbrech/climbing-wall