
name: CI

on:
  create:
    tags:
      - v*

jobs:
  
  conda-bld:
    
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]
      fail-fast: false
    
    runs-on: ${{ matrix.os }}    

    steps:
    - uses: actions/checkout@v2

    - name: Add conda to path (ubuntu, macos)
      run: |
        echo "::add-path::$CONDA/bin"
        export PATH=$CONDA/bin:$PATH
        conda init bash
      if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
    - name: Add conda to path (windows)
      run: |
        echo "::add-path::$env:CONDA\Scripts"
        $env:Path += ";$env:CONDA\Scripts"
        conda init powershell
      if: contains(matrix.os, 'windows')
    - name: MacOS Conda Ownership Workaround (macos)
      run: sudo chown -R $USER $CONDA
      if: contains(matrix.os, 'macos')
    
    - name: update conda, install conda-build and anaconda-client
      run: |
        conda update -q conda
        conda install conda-build anaconda-client
        conda info -a
        conda list -n base
        
    - name: build BYOW package (ubuntu, macos)
      run: |
        conda-build conda-recipe -c joergbrech
      if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
    - name: build BYOW package (windows)
      run: |
        conda-build conda-recipe -c joergbrech
      shell: cmd
      if: contains(matrix.os, 'windows')
    
    - name: Copy builds (ubuntu)
      run: |
        mkdir -p build
        cp /usr/share/miniconda/conda-bld/linux-64/*.tar.bz2 build/
      if: contains(matrix.os, 'ubuntu')
      
    - name: Copy builds (macos)
      run: |
        mkdir -p build
        cp /usr/local/miniconda/conda-bld/osx-64/*.tar.bz2 build/
      if: contains(matrix.os, 'macos')
    
    - name: Copy builds (windows)
      run: |
        if not exist "build" mkdir build
        Copy C:\Miniconda\conda-bld\win-64\*.tar.bz2 build
      shell: cmd
      if: contains(matrix.os, 'windows')
      
    - name: Upload packages as artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: conda-package
        path: build
        
    - name: Publish to anaconda (ubuntu, macos)
      run: |
        anaconda login --username joergbrech --password ${{ secrets.ANACONDA_PWD }}
        anaconda upload build/*
      
